--- 
# project options

# pepStat options
mapping: mapping.csv
collection: pep_hxb2
method: absolute
call.cutoff: 0.1

# HIV.db options
genome: hxb2
features:
  - V1
  - V2
  - V3
  - ID
  - MPER
  - TM
