```{r knitr-opts, echo=FALSE}
library(knitr)
opts_chunk$set(message=TRUE)
```

```{r libraries, echo=FALSE, message=FALSE}
library(pepStat)
library(PEP.db)
library(HIV.db)
library(Pviz)
library(yaml)
```

## Reading the option file
```{r read-config}
yaml_opts <- yaml.load_file("../settings/config.yaml")
projdir <- yaml_opts$projdir
mappingfilename <- yaml_opts$mapping
#pepStat opts
collection <- get(eval(substitute(data(x), list(x=yaml_opts$collection))))
method <- yaml_opts$method
call.cutoff <- yaml_opts$call.cutoff
#HIV.db opts
genome <- yaml_opts$genome
features <- yaml_opts$features
```

## Generating a peptideSet
```{r makePeptideSet, cache=TRUE, dependson="read.config"}
pSet <- makePeptideSet(files=NULL, path=paste(projdir, "data", "input", sep="/"), mapping.file=paste(projdir, "data", "input", mappingfilename, sep="/"))
```

## Summarizing within-slide replicates
```{r summarizePeptides, cache=TRUE, dependson="makePeptideSet"}
psSet <- summarizePeptides(pSet,summary="median", position=collection)
```

## Normalizing the peptideSet
```{r NormalizeArray}
pnSet <- normalizeArray(psSet)
write.pSet(pnSet, bg.correct=TRUE, file=paste(projdir, "data/output/pnset.csv", sep="/"))
write.pSet(pnSet, bg.correct=TRUE, file=paste(projdir, "data/output/pnset_corrected.csv", sep="/"))
```

## Data smoothing
```{r slidingMean}
pnmSet <- slidingMean(pnSet)
write.pSet(pnSet, bg.correct=TRUE, file=paste(projdir, "data/output/pnmset.csv", sep="/"))
write.pSet(pnSet, bg.correct=TRUE, file=paste(projdir, "data/output/pnmset_corrected.csv", sep="/"))
```

## Making calls
```{r makeCalls}
freq <- makeCalls(pnmSet, cutoff=call.cutoff, group=NULL, method=method)
```

## Query annotations
```{r annotations}
anno_db<-loadFeatures(genome=genome)
features <- getFeature(anno_db, name=features)
```

## Tracks creation
```{r Pviz-tracks}
pat <- ProteinAxisTrack(addNC=TRUE, littleTicks=TRUE)
anno <- ATrack(start=start(features), end=end(features), name=getName(features))

```
<!--
```{r evalF, eval=FALSE, echo=FALSE}
hotspot <- pepStat::.reduce2hotspots <- function(pSet, freq, hotspot.cutoff=.2)
  
  pnSet.clade <- split(pnSet, clade(pnSet))

pnmSet.clade <- lapply(pnSet.clade,slidingMean)

freq.clade <- lapply(pnmSet.clade, makeCalls, cutoff=call.cutoff, group=NULL, method=method) # This could come from a config file

## Generate annotation tracks


#make a track for AA seqence
Axis <- ProteinAxisTrack(fontsize=16, littleTicks=TRUE, addNC=TRUE)

# Get the frame of the env protein
proteins <- getFeature(anno_db, category="protein")
pro_anno <- AnnotationTrack(start=start(proteins),end=end(proteins), id=proteins$name, genome=genome, name="", chromosome="chr", fill=colorAnno[3:4],size=1.5, fontcolor="black", fontsize=16)
displayPars(pro_anno) <- list(background.panel = colorAnno[1], alpha=1, showFeatureId=TRUE, stacking="dense", rotation=0, background.title="white", fontcolor="black")

## Specific annotations for each genome

landmarks <- getFeature(anno_db,name=c("V1","V2","V3","V4","V5","ID","MPER","TM"))
...

## Add a legend if group is not NULL
plotTracks(c(landmarks_anno,freq))

### These should be repeated for the clade specific stuff
```
-->