%\VignetteIndexEntry{The pepStat users guide}
%\VignetteDepends{}
%\VignetteKeywords{Preprocessing, Affymetrix}
%\VignettePackage{pepStat}
\documentclass[11pt]{article}
\usepackage{hyperref}
\usepackage{url}
\SweaveOpts{keep.source=FALSE}

\title{The pepStat user guide}
\author{Raphael Gottardo\footnote{rgottard@fhcrc.org}, Mike Jiang\footnote{wjiang2@fhcrc.org} and Renan Sauteraud\footnote{rsautera@fhcrc.org}}

\begin{document}
\maketitle



\textnormal {\normalfont}
A step-by-step guide in the analysis of peptide microarray antibody binding

\tableofcontents
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage

\section{Generating a peptideSet}

%<<makePepideSet>>=
%mapping<-system.file(
%pSet<-makePeptideSet(
%@


\end{document}
