%\VignetteIndexEntry{The pepStat users guide}
%\VignetteDepends{PEP.db}
%\VignetteKeywords{Preprocessing, Affymetrix}
%\VignettePackage{pepStat}
\documentclass[11pt]{article}
\usepackage{hyperref}
\usepackage{url}
\SweaveOpts{keep.source=FALSE}

\title{The pepStat user guide}
\author{Raphael Gottardo\footnote{rgottard@fhcrc.org}, Mike Jiang\footnote{wjiang2@fhcrc.org} and Renan Sauteraud\footnote{rsautera@fhcrc.org}}

\begin{document}
\maketitle



\textnormal {\normalfont}
A step-by-step guide in the analysis of peptide microarray antibody binding

\tableofcontents
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{Introduction}

As with any R package, it should first be loaded in the session.
<<loading-pakage>>=
library(pepStat)
@

\section{Generating a peptideSet}

The reading function takes a path as its argument and parse all the files in the given directory.

<<makePepideSet>>=
mapFile<-system.file("extdata/mapping.csv", package="pepStat")
dirToParse<-system.file("extdata/RVV", package="pepStat")
pSet<-makePeptideSet(files=NULL, path=dirToParse, mapping.file=mapFile, rm.control.list=c("empty","none","JPT-","Ig","Cy","landmark"),log=TRUE,verbose=TRUE)
@

A new object of class \texttt{peptideSet}. It contins only the sequence of the peptides and the intensities measured. Any additional information must be passed using a known collection of peptides. In this example, we use pep\_hxb2 available in the \texttt{PEP.db} package.

<<adding-positions>>=
library(PEP.db)
data(pep_hxb2)
psSet<-summarizePeptides(pSet, summary="mean", position=pep_hxb2)
@

pep\_hxb2 gives information regarding the position of each peptide, their z-scores, the clades they belong to and the alignment with the reference sequence HXB2.


\section{Normalizing the peptideSet}
<<normalize>>=
pnSet<-NormalizeArray(psSet, verbose=TRUE)
@


\section{Making calls}

<<makeCalls>>=
Vsum<-subset(psSet, treatment!="PLACEBO")
Vnorm<-subset(pnSet, treatment!="PLACEBO")
V_smooth<-slidingMean(Vnorm, width=9)

cutoff<-1.1
V_calls<-makeCalls(V_smooth,cutoff=cutoff,method="absolute")
@




\end{document}
